FROM python:3.11
ENV PYTHONBUFFRED 1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python -m pip install django-mysql
RUN python -m pip install django-cors-headers
COPY . /app
CMD python manage.py runserver 0.0.0.0:8000

